### ISSUE TITLE
CSV Logs don’t display correctly.

### ISSUE THREAD

**Issue by chhayse7en** [mason1901/ikoa-web#11]
CSV Logs don’t display correctly like in the picture.
![937DF3CB-505E-459D-B33E-00480CE33192](https://user-images.githubusercontent.com/69116277/90112917-d2c38900-dd7a-11ea-9bac-19849ebaa7d3.jpeg)

**Comment by mason1901** [comment]
Fixed.

**Comment by chhayse7en** [comment]
> Fixed.
It’s not fully fixed yet as the errors still persist like in these pics.


![3A8621B8-9363-4451-BED9-E6C33560CEEA](https://user-images.githubusercontent.com/69116277/90233449-61520c00-de48-11ea-8b9c-2d0a03cc6e8e.jpeg)

![IMG_0046](https://user-images.githubusercontent.com/69116277/90233254-0cae9100-de48-11ea-96a1-18bc5784c4ea.jpeg)
